# Generated by Django 4.2.3 on 2023-07-25 16:06

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCuriosidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(verbose_name='Criação')),
                ('edicao', models.DateTimeField(auto_now_add=True, verbose_name='Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.CharField(max_length=300, verbose_name='Resumo')),
                ('link', models.CharField(max_length=300, verbose_name='Link')),
                ('capa', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumbnail': {'crop': True, 'height': 260, 'width': 374}})),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
